---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy index settings and mappings
      template:
        src: "../../ansible_templates/control_scripts/elasticsearch/{{ item }}"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/elasticsearch/{{ item }}"
        mode: 0777
      with_items:
        - standard_index_mapping.json
        - standard_index_settings.json
      tags:
        - 700_prepare_indexing

    - name: Copy index creation script
      template:
        src: "../../ansible_templates/control_scripts/elasticsearch/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/elasticsearch/{{ item }}"
        mode: 0777
      with_items:
        - create_index.rb
      tags:
        - 700_prepare_indexing

    - name: Create index
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/elasticsearch"
      with_items:
        - create_index.rb
      tags:
        - 700_prepare_indexing
