---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: COPY index_cookbook_entities.rb
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - index_cookbook_entities.rb
      tags:
        - 712_index_cookbook_entities

    - name: RUN index_cookbook_entities.rb
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - index_cookbook_entities.rb
      tags:
        - 714_index_cookbook_entities
