---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: COPY index_dataspectsSystem_instance_source_folder.rb
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - index_dataspectsSystem_instance_source_folder.rb
      tags:
        - 720_index_dataspectsSystem_instance_source_folder

    - name: RUN index_dataspectsSystem_instance_source_folder
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - index_dataspectsSystem_instance_source_folder.rb
      tags:
        - 720_index_dataspectsSystem_instance_source_folder
