---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: 300 Clone required mediawiki version
      shell: "git clone --branch {{ mediawiki_version }} --depth 1 --single-branch https://github.com/wikimedia/mediawiki.git w/"
      args:
        chdir: "/home/dataspects/mediawiki_root"
      become: "true"
      tags:
        - 300_install_mediawiki

    - name: 300 Install core extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "/home/dataspects/mediawiki_root/w/"
      become: "true"
      tags:
        - 300_install_mediawiki

    - name: 300 Place composer install script
      template:
        src: ../../ansible_templates/install_composer.sh
        dest: "/home/dataspects/mediawiki_root/w/install_composer.sh"
        mode: 0777
      become: "true"
      tags:
        - 301_install_composer

    - name: 300 Install composer locally
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "cd /var/www/html/w && ./install_composer.sh"
      become: "true"
      tags:
        - 301_install_composer

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Run composer inside container
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "cd /var/www/html/w && php composer.phar install"
      become: "true"
      tags:
        - 302_run_composer

    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Place mediawiki install script
      template:
        src: ../../ansible_templates/install_mediawiki.sh.j2
        dest: "/home/dataspects/mediawiki_root/w/install.sh"
        mode: 0777
      become: "true"
      tags:
        - 300_install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Install mediawiki inside container
      shell: "docker exec {{ mediawikiDockerServiceName }} bash -c 'cd /var/www/html/w && ./install.sh'"
      become: "true"
      tags:
        - 300_install_mediawiki

    - name: 300 Add settings to LocalSettings.php
      lineinfile:
        path: "/home/dataspects/mediawiki_root/w/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - $wgArticlePath = '/wiki/$1';
        - $wgFileExtensions[] = 'pdf';
      become: "true"
      tags:
        - 300_install_mediawiki

    #FIXME: This should replace, but it actually just adds!
    - name: 300 Replace settings in LocalSettings.php
      lineinfile:
        path: "/home/dataspects/mediawiki_root/w/LocalSettings.php"
        regexp: '{{ item.orig }}'
        line: '{{ item.replace }}'
      with_items:
        - { orig: "^$wgServer = ", replace: '$wgServer = "http://local.mediawiki";' }
        - { orig: "^$wgEnableUploads = ", replace: '$wgEnableUploads = true;' }
      become: "true"
      tags:
        - 300_install_mediawiki
        - t1811161102t

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Change admin user password
      shell: docker exec {{ mediawikiDockerServiceName }} bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: "true"
      tags:
        - 300_install_mediawiki

    #FIXME: This should replace, but it actually just adds!
    - name: 300 Replace settings in LocalSettings.php
      lineinfile:
        path: "/home/dataspects/mediawiki_root/w/LocalSettings.php"
        regexp: '{{ item.orig }}'
        line: '{{ item.replace }}'
      with_items:
        - { orig: "^$wgServer = ", replace: '$wgServer = "http://{{ mediawikiDomainNameInHostFile }}:{{ nginxPortOnHost }}";' }
        - { orig: "^$wgEnableUploads = ", replace: '$wgEnableUploads = true;' }
      become: "true"
      tags:
        - 300_install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Set permissions on mediawiki root
      file:
        path: "/home/dataspects/mediawiki_root/w/"
        owner: www-data
        recurse: yes
      become: "true"
      when:
        platform == 'linux'
      tags:
        - 300_install_mediawiki

    - name: 300 execute_mediawiki_maintenance_runJobs
      shell: docker exec {{ mediawikiDockerServiceName }} bash -c "php w/maintenance/runJobs.php"
      become: yes
      tags:
        - 300_install_mediawiki
