---

- hosts: localhost
  gather_facts: False
  tasks:

    ############################################################################
    - name: 300 Register {{ dataspectsSystem_control_folder_on_host | basename | lower }}_mediawiki_root path on host
      shell: docker volume inspect {{ dataspectsSystem_control_folder_on_host | basename | lower }}_mediawiki_root
      register: volume_profile
      when: docker_volumes_mode == 'automatic'
      become: yes
      become_method: sudo
      tags:
        - 300_install_mediawiki
    - set_fact: mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')).values() | first }}
      when: docker_volumes_mode == 'automatic'
      tags:
        - 300_install_mediawiki
    - set_fact: mountpoint={{ manual_docker_volumes_location }}mediawiki_root
      when: docker_volumes_mode == 'manual'
      tags:
        - 300_install_mediawiki
    ############################################################################

    - name: 300 Clone required mediawiki version
      shell: "git clone --branch {{ mediawiki_version }} --depth 1 --single-branch https://github.com/wikimedia/mediawiki.git w/"
      args:
        chdir: "{{ mountpoint }}"
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    - name: 300 Install core extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "{{ mountpoint }}/w/"
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    - name: 300 Place composer install script
      template:
        src: ../../ansible_templates/install_composer.sh
        dest: "{{ mountpoint }}/w/install_composer.sh"
        mode: 0777
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    - name: 300 Install composer locally
      shell: docker exec {{ systemPrefix }}-{{ mediawikiDockerServiceName }} bash -c "cd /var/www/html/w && ./install_composer.sh"
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Run composer inside container
      shell: docker exec {{ systemPrefix }}-{{ mediawikiDockerServiceName }} bash -c "cd /var/www/html/w && php composer.phar install"
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Place mediawiki install script
      template:
        src: ../../ansible_templates/install_mediawiki.sh.j2
        dest: "{{ mountpoint }}/w/install.sh"
        mode: 0777
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Install mediawiki inside container
      shell: "docker exec {{ systemPrefix }}-{{ mediawikiDockerServiceName }} bash -c 'cd /var/www/html/w && ./install.sh'"
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    - name: 300 Add settings to LocalSettings.php
      lineinfile:
        path: "{{ mountpoint }}/w/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - $wgArticlePath = '/wiki/$1';
        - $wgFileExtensions[] = 'pdf';
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    #FIXME: This should replace, but it actually just adds!
    - name: 300 Replace settings in LocalSettings.php
      lineinfile:
        path: "{{ mountpoint }}/w/LocalSettings.php"
        regexp: '{{ item.orig }}'
        line: '{{ item.replace }}'
      with_items:
        - { orig: "^$wgServer = ", replace: '$wgServer = "http://local.mediawiki";' }
        - { orig: "^$wgEnableUploads = ", replace: '$wgEnableUploads = true;' }
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki
        - t1811161102t

    # [[IsOperationType::VendorPackageOperation]]
    - name: 300 Change admin user password
      shell: docker exec {{ systemPrefix }}-{{ mediawikiDockerServiceName }} bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    #FIXME: This should replace, but it actually just adds!
    - name: 300 Replace settings in LocalSettings.php
      lineinfile:
        path: "{{ mountpoint }}/w/LocalSettings.php"
        regexp: '{{ item.orig }}'
        line: '{{ item.replace }}'
      with_items:
        - { orig: "^$wgServer = ", replace: '$wgServer = "http://{{ mediawikiDomainNameInHostFile }}:{{ nginxPortOnHost }}";' }
        - { orig: "^$wgEnableUploads = ", replace: '$wgEnableUploads = true;' }
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 300_install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: 300 Set permissions on mediawiki root
      file:
        path: "{{ mountpoint }}/w/"
        owner: www-data
        recurse: yes
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      when:
        platform == 'linux'
      tags:
        - 300_install_mediawiki

    - name: 300 execute_mediawiki_maintenance_runJobs
      shell: docker exec {{ systemPrefix }}-{{ mediawikiDockerServiceName }} bash -c "php w/maintenance/runJobs.php"
      become: yes
      tags:
        - 300_install_mediawiki
