---

- hosts: localhost
  gather_facts: False
  tasks:

    # FIXME: Only run this if docker_network_mode IS NOT "host"

    ############################################################################
    # 310_configure_proxy ##########################################################
    - name: Register {{ dataspectsSystem_control_folder_on_host | basename | lower }}_nginx_conf path on host
      shell: docker volume inspect {{ dataspectsSystem_control_folder_on_host | basename | lower }}_nginx_conf
      register: volume_profile
      when: docker_volumes_mode == 'automatic'
      tags:
        - 310_configure_proxy
    - set_fact: mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')).items()[0][1] }}
      when: docker_volumes_mode == 'automatic'
      tags:
        - 310_configure_proxy
    - set_fact: mountpoint={{ manual_docker_volumes_location }}nginx_conf
      when: docker_volumes_mode == 'manual'
      tags:
        - 310_configure_proxy

    - name: Place mediawiki service nginx conf
      template:
        src: ../../ansible_templates/mediawiki-nginx.conf.j2
        dest: "{{ mountpoint }}/mediawiki-nginx.conf"
        mode: 0777
      become: "{{ 'true' if platform == 'linux' else 'false' }}"
      tags:
        - 310_configure_proxy

    - name: Restart Nginx Proxy
      shell: docker-compose \
               --file {{ dataspectsSystem_control_folder_on_host }}/docker-compose.yml \
                 restart proxy
      tags:
        - 310_configure_proxy
