---

- hosts: localhost
  gather_facts: False
  tasks:
  
    - name: 320 Place MediaWiki extensions list
      template:
        src: ../../ansible_templates/mediawiki_extensions.yml.j2
        dest: "/home/dataspects/mediawiki_root/w/mediawiki_extensions.yml"
        mode: 0777
      become: "true"
      tags:
        - 320_install_mediawiki_extensions

    - name: 320 Place MediaWiki extensions install script
      template:
        src: ../../ansible_templates/install_mediawiki_extensions.rb.j2
        dest: "/home/dataspects/mediawiki_root/w/install_mediawiki_extensions.rb"
        mode: 0777
      become: "true"
      tags:
        - 320_install_mediawiki_extensions

    - name: 320 Install MediaWiki extensions
      shell: ruby install_mediawiki_extensions.rb
      args:
        chdir: "/home/dataspects/mediawiki_root/w/"
      become: "true"
      tags:
        - 320_install_mediawiki_extensions

    # [[IsOperationType::FileSystemOperation]]
    - name: 320 Set permissions on mediawiki root
      file:
        path: "/home/dataspects/mediawiki_root/w/"
        owner: www-data
        recurse: yes
      become: "true"
      tags:
        - 320_install_mediawiki_extensions
