---

- hosts: localhost
  gather_facts: False
  tasks:

    ############################################################################
    - name: Register {{ dataspectsSystem_control_folder_on_host | basename | lower }}_mediawiki_root path on host
      shell: docker volume inspect {{ dataspectsSystem_control_folder_on_host | basename | lower }}_mediawiki_root
      register: volume_profile
      tags:
        - 320_install_mediawiki_extensions
    - set_fact: "mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}"
      tags:
        - 320_install_mediawiki_extensions
    ############################################################################

    - name: Place MediaWiki extensions list
      template:
        src: ../../ansible_templates/mediawiki_extensions.yml.j2
        dest: "{{ mountpoint.items()[0][1] }}/w/mediawiki_extensions.yml"
        mode: 0777
      become: true
      tags:
        - 320_install_mediawiki_extensions

    - name: Place MediaWiki extensions install script
      template:
        src: ../../ansible_templates/install_mediawiki_extensions.rb.j2
        dest: "{{ mountpoint.items()[0][1] }}/w/install_mediawiki_extensions.rb"
        mode: 0777
      become: true
      tags:
        - 320_install_mediawiki_extensions

    - name: Install MediaWiki extensions
      shell: ruby install_mediawiki_extensions.rb
      args:
        chdir: "{{ mountpoint.items()[0][1] }}/w/"
      become: true
      tags:
        - 320_install_mediawiki_extensions
