version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
      - "discovery.type=single-node"
    volumes: #FIXME esdata needs special permissions! Hack: chmod -R 777 ./elasticsearch_data
      - /home/dataspects/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: host
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://127.0.0.1:9200"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    network_mode: host
  neo4j:
    container_name: neo4j
    image: neo4j:4.1.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_active__database=dataspectsNeo4j.db
    volumes:
      - /home/dataspects/neo4j_data:/data
  mediawiki:
    container_name: mediawiki
    image: mediawiki:lts
    container_name: mediawiki
    ports:
      - 80:80
    volumes:
      - /home/dataspects/mediawiki_root:/var/www/html/
    network_mode: host
