version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
      - "discovery.type=single-node"
    volumes: #FIXME esdata needs special permissions! Hack: chmod -R 777 ./elasticsearch_data
      - /home/ds/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: host
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://127.0.0.1:9200"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    network_mode: host
  neo4j:
    container_name: neo4j
    image: neo4j:4.1.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_active__database=dataspectsNeo4j.db
    volumes:
      - /home/ds/neo4j_data:/data
    network_mode: host
  mediawiki:
    container_name: mediawiki
    image: dataspects/docker-apache-php-dataspects-mediawiki:1.3
    ports:
      - 80:80
    volumes:
      - /home/ds/mediawiki_root:/var/www/html/
    network_mode: host
  mysql:
    container_name: mysql
    image: mysql:8.0.20
    volumes:
      - /home/ds/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpassword
    network_mode: host
  parsoid:
    container_name: parsoid
    image: dataspects/docker-parsoid:0.10.0
    environment:
      - PARSOID_DOMAIN_dataspects=http://127.0.0.1/w/api.php
    network_mode: host