---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy search contexts
      copy:
        src: "../../ansible_templates/control_scripts/search_contexts/{{ item }}"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/search_contexts/{{ item }}"
        mode: 0777
      with_items:
        - features.json
        - general.json
        - support.json
      tags:
        - configure_nodejsSTOP

    - name: Copy NodeJS configuration job
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - add_mediawiki_instance_to_mongodb.rb
        #- add_search_contexts_to_mongodb.rb
      tags:
        - configure_nodejs

    - name: Execute jobs
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - add_mediawiki_instance_to_mongodb.rb
        #- add_search_contexts_to_mongodb.rb
      tags:
        - configure_nodejsSTOP
