---

- hosts: localhost
  gather_facts: False
  tasks:

    - pause:
        prompt: "Please make sure RubyGem 'dataspects' is installed on your system. See https://github.com/dataspects/dataspects. When ready press ENTER..."
      tags:
        - 400_provision_as_cookbookfalnet

    - name: Copy provision jobs
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - inject_core_ontology.rb
        - inject_cookbook_ontology.rb
        - inject_cookbook_entities.rb
      tags:
        - 400_provision_as_cookbookfalnet

    - name: Execute provision jobs
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - inject_core_ontology.rb
        - inject_cookbook_ontology.rb
        - inject_cookbook_entities.rb
      tags:
        - 400_provision_as_cookbookfalnet
