---

- hosts: localhost
  gather_facts: False
  tasks:

  - name: Place python3 webserver script
    template:
      src: ../../ansible_templates/control_scripts/dataspects_search.sh.j2
      dest: "/home/ds/dataspects_search.sh"
      mode: 0777
    tags:
      - 500_install_dataspects_search
  
  - name: Create dataspects search root folder
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /home/ds/search
    tags:
      - 500_install_dataspects_search