---

- hosts: localhost
  gather_facts: False
  tasks:

    - pause:
        prompt: Press ENTER when nodemon is running...
      tags:
        - 500_configure_nodejs

    - debug:
        msg: "{{ dataspectsui_email }}"
      tags:
        - 500_configure_nodejs

    - name: COPY NodeJS users
      template:
        src: "../../ansible_templates/control_scripts/users/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/users/{{ item }}"
        mode: 0777
      with_items:
        - admin.json
      tags:
        - 500_configure_nodejs

    - name: COPY NodeJS configuration jobs
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - add_mediawiki_instance_to_mongodb.rb
        - add_users_to_mongodb.rb
      tags:
        - 500_configure_nodejs

    - name: RUN NodeJS configuration jobs
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - add_mediawiki_instance_to_mongodb.rb
        - add_users_to_mongodb.rb
      ignore_errors: yes
      tags:
        - 500_configure_nodejs
