---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: COPY NodeJS search contexts
      copy:
        src: "../../ansible_templates/control_scripts/search_contexts/{{ item }}"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/search_contexts/{{ item }}"
        mode: 0777
      with_items:
        - features.json
        - general.json
        - support.json
      tags:
        - 500_configure_nodejs
      #FIXME: https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names

    - name: COPY NodeJS configuration jobs
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - add_mediawiki_instance_to_mongodb.rb
        #- add_search_contexts_to_mongodb.rb
      tags:
        - 500_configure_nodejs

    - name: RUN NodeJS configuration jobs
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - add_mediawiki_instance_to_mongodb.rb
        #- add_search_contexts_to_mongodb.rb
      tags:
        - 500_configure_nodejs
