---

- hosts: localhost
  gather_facts: False
  tasks:

    - debug:
        msg: "DOCKER_VOLUMES_MODE={{ docker_volumes_mode }}"
      tags:
        - 200_compile_and_copy_docker_compose_file

    - name: Set Docker volumes location
      set_fact:
        manual_docker_volumes_location: "{{ dataspectsSystem_control_folder_on_host }}/"
        comment_out_volumes: "#"
      when: docker_volumes_mode == 'manual'
      tags:
        - 200_compile_and_copy_docker_compose_file

    - name: Set Docker volumes location
      set_fact:
        manual_docker_volumes_location: ""
        comment_out_volumes: ""
      when: docker_volumes_mode == 'automatic'
      tags:
        - 200_compile_and_copy_docker_compose_file

    - debug:
        msg: "manual_docker_volumes_location = {{ manual_docker_volumes_location }}"
      tags:
        - 200_compile_and_copy_docker_compose_file

    - name: Copy docker-compose.yml file to {{ dataspectsSystem_control_folder_on_host }}
      template:
        src: ../../ansible_templates/docker-compose/docker-compose.yml.j2
        dest: "{{ dataspectsSystem_control_folder_on_host }}/docker-compose.yml"
      tags:
        - 200_compile_and_copy_docker_compose_file
