---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy control files
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - compare.rb
      tags:
        - 900_compare

    - name: Compare ontologies
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - compare.rb
      tags:
        - 900_compare
