---

- hosts: localhost
  gather_facts: False
  tasks:

    - pause:
        prompt: "Please ensure that https://github.com/dataspects/dataspects-file-feeder/releases is present in {{ dataspectsSystem_control_folder_on_host }}. When ready press ENTER..."
      tags:
        - 610_feed_dataspectsSystem_source_folder

    - name: CHECK if "{{ dataspectsSystem_control_folder_on_host }}/dataspects-file-feeder" exists
      stat:
        path: "{{ dataspectsSystem_control_folder_on_host }}/dataspects-file-feeder"
      register: dataspects_file_feeder_exists
      tags:
        - 610_feed_dataspectsSystem_source_folder

    - fail:
        msg: "{{ dataspectsSystem_control_folder_on_host }}/dataspects-file-feeder not found, download from https://github.com/dataspects/dataspects-file-feeder/releases"
      when: dataspects_file_feeder_exists.stat.exists == False
      tags:
        - 610_feed_dataspectsSystem_source_folder

    - name: COPY dataspects-file-feeder items
      template:
        src: ../../ansible_templates/{{ item }}.j2
        dest: "{{ dataspectsSystem_control_folder_on_host }}/{{ item }}"
      with_items:
        - control_scripts/dataspects-file-feeder-config.json
        - control_scripts/feed_dataspectsSystem_instance_source_folder.sh
      tags:
        - 610_feed_dataspectsSystem_source_folder

    - name: Make executable control_scripts/feed_dataspectsSystem_instance_source_folder.sh
      file:
        path: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/feed_dataspectsSystem_instance_source_folder.sh"
        mode: 0777
      tags:
        - 610_feed_dataspectsSystem_source_folder

    - name: RUN dataspects-file-feeder
      shell: control_scripts/feed_dataspectsSystem_instance_source_folder.sh
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}"
      when: dataspects_file_feeder_exists.stat.exists == True
      tags:
        - 610_feed_dataspectsSystem_source_folder
