- hosts: localhost
  gather_facts: False
  tasks:

    - name: Create dataspectsSystem_control_folder_on_host and subfolders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dataspectsSystem_control_folder_on_host }}"
        - "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/"
        - "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/elasticsearch"
        - "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/search_contexts"
      tags:
        - create_dataspectsSystem_control_folder_on_host

    - debug:
        msg:
          - "Your custom dataspectsSystem name: {{ dataspectsSystem_control_folder_on_host | basename }}"
          - "Your custom dataspectsSystem location: {{ dataspectsSystem_control_folder_on_host }}"
      tags:
        - create_dataspectsSystem_control_folder_on_host
