---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy feeding job
      template:
        src: "../../ansible_templates/control_scripts/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts/{{ item }}"
        mode: 0777
      with_items:
        - feed_dataspectsSystem_source_folder.rb
      tags:
        - feed_dataspectsSystem_source_folder

    - name: Check if "{{ dataspectsSystem_control_folder_on_host }}/dataspects-indexer" exists
      stat:
        path: "{{ dataspectsSystem_control_folder_on_host }}/dataspects-indexer"
      register: dataspects_indexer_exists
      tags:
        - feed_dataspectsSystem_source_folder

    - fail:
        msg: "{{ dataspectsSystem_control_folder_on_host }}/dataspects-indexer not found, download from https://github.com/dataspects/dataspects-indexer/releases"
      when: dataspects_indexer_exists.stat.exists == False
      tags:
        - feed_dataspectsSystem_source_folder

    - name: Place dataspects-indexer-config.json
      template:
        src: ../../ansible_templates/dataspects-indexer-config.json.j2
        dest: "{{ dataspectsSystem_control_folder_on_host }}/dataspects-indexer-config.json"
      tags:
        - feed_dataspectsSystem_source_folder

    - name: Run dataspects-indexer
      shell: ./dataspects-indexer --config dataspects-indexer-config.json --indexer cofal
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}"
      when: dataspects_indexer_exists.stat.exists == True
      tags:
        - feed_dataspectsSystem_source_folderSTOP
