---
label: dataspectsd
regex: \.go$
config:
  tasks:
    - name: Analyze dependencies
      actions:
        annotation:
            - contentRegex: "import *\\(([\"\\w\\/.\\n\\t ]*?)\\)"
              predicate: DependsOn
              object: 1
              splitObjectIntoValues: \n
    - name: Analyze actions
      actions:
        annotation:
            - contentRegex: "type Actions struct *\\{([\"\\w\\[\\]`:.\\n\\t ]*?)\\}"
              predicate: ProvidesAction
              object: 1
              splitObjectIntoValues: \n