---
version: 1.0
tasks:
  - name: Analyze mainspace pages
    actions:
      - name: ResourceNameMatches
        argument:
            resourceName: actions.go
        actions:
          - name: EntitizeByRegex
            argument:
                regex: 'case "([\w]*)": \/\/(.*)'
                entity:
                    HasEntityName: _regex(match[0][1])
                    HasEntityContentSource: _regex(match[0][2])
          - name: IndexFileHavingRegex
            argument:
                regex: '\[\[(\w+)::(.*?)\]\]'
                turnRegexIntoAnnotations:
                  predicate: _regex(match[1])
                  object: _regex(match[2])
          - name: EntitizeByRegex
            argument:
                regex: 'type (.*) (struct)'
                entity:
                    HasEntityName: _regex(match[0][1])
                    HasEntityContentSource: _regex(match[0][2])