---
version: 1.0
tasks:
  - name: Analyze mainspace pages
    actions:
      entitizeByRegex:
        - regex: 'case "([\w]*)": \/\/(.*)'
          hasEntityName: 1
          hasEntityContentSource: 2
          predicate: HasArgument
          object: 2
      indexFileHavingRegexWithLocationPredicate:
        - regex: '\[\[(\w+)::(.*?)\]\]'
          predicate: 1
          object: 2
      indexFileHavingRegexWithStringPredicate:
        - regex: '\[\[\w+::(.*?)\]\]'
          predicate: HasColor
          object: 1
          actions:
            fileContentMatchingRegex:
              - regex: 'the[Ss]tring'
                facetTag: foo